### PR TITLE
start dockerization

### PR DESCRIPTION
**Pull request by joofio**
@aalonsolopez , @gmej i think it can be just something like this? I just need the part of how to send the data to the script. i see at least 4 possibilities but i dont quite know how to do it:

- Environment Variables: Pass the data as environment variables when starting the container.
- Input Files: Mount a volume containing JSON or other data files, then load these files into your JavaScript code.
- API or HTTP Server: You could set up an API within the Docker container and send the data via HTTP requests.
- Interactive Input: Provide the data by reading from a file or standard input.

opinions?

### CODE REVIEW

**Comment by joofio** [comment]
additional comments, the github workflow would rely on a dockerhub user and password as env secret. if other registry we need to change that

**Comment by gmej** [comment]
1. We can use the image registry that we have for gravitate health, better than GHCR.  I'm almost sure that we will hit the limit for our plan in Github regarding traffic or space. The one we have is "unlimited" for Gravitate Health.
2. Regarding this, I think for Docker the best practice would be serving an API. This way we can deeply test the container without having to restart it. This way you cn change the ePI and IPS in the request directly.

**Comment by joofio** [comment]
i would argue with the API format, but that would involve changing the current code (I guess)

**Comment by joofio** [comment]
please see image v2 as template for own registry

**Comment by joofio** [comment]
added uploader

**Pull request closed without merging**
